6898 get iLeapp to work on other disk images and logical file sets
sleuthkit/autopsy pull request #6397
Opened 2020-10-19 13:33 UTC by markmckinnon

2020-11-06 19:19 UTC, kellykelly3 requested changes

2020-11-06 19:19 UTC, kellykelly3 commented on Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java
> +    private void processILeappFs(Content dataSource, Case currentCase, DataSourceIngestModuleProgress statusHelper, String directoryToProcess) {
Missing method header

2020-11-06 19:19 UTC, kellykelly3 commented on Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java
> +    private ProcessBuilder buildiLeappListCommand(Path moduleOutputPath) {
Method header.

2020-11-06 19:19 UTC, kellykelly3 commented on Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java
> +    private List<String> loadIleappPathFile(Path moduleOutputPath) throws FileNotFoundException, IOException {
Add @param to method header.

2020-11-06 19:19 UTC, kellykelly3 commented on Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java
> +    private void extractFilesFromImage(Content dataSource, List<String> iLeappPathsToProcess, Path moduleOutputPath) {
method header.

2020-11-06 19:19 UTC, kellykelly3 commented on Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java
> +    private void extractFileToOutput(Content dataSource, AbstractFile iLeappFile, File fileParentPath, Path parentPath) {
method header

2020-11-06 19:19 UTC, kellykelly3 commented on Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java
> +    private void writeiLeappFile(Content dataSource, AbstractFile iLeappFile, String parentPath) {
method header.

2020-11-19 00:46 UTC, markmckinnon commented on Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java
> +    private void processILeappFs(Content dataSource, Case currentCase, DataSourceIngestModuleProgress statusHelper, String directoryToProcess) {
Done

2020-11-19 00:46 UTC, markmckinnon commented on Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java
> +    private ProcessBuilder buildiLeappListCommand(Path moduleOutputPath) {
Done

2020-11-19 00:47 UTC, markmckinnon commented on Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java
> +    private List<String> loadIleappPathFile(Path moduleOutputPath) throws FileNotFoundException, IOException {
Done

2020-11-19 00:47 UTC, markmckinnon commented on Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java
> +    private void extractFilesFromImage(Content dataSource, List<String> iLeappPathsToProcess, Path moduleOutputPath) {
Done

2020-11-19 00:47 UTC, markmckinnon commented on Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java
> +    private void extractFileToOutput(Content dataSource, AbstractFile iLeappFile, File fileParentPath, Path parentPath) {
Done

2020-11-19 00:47 UTC, markmckinnon commented on Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java
> +    private void writeiLeappFile(Content dataSource, AbstractFile iLeappFile, String parentPath) {
Done

2020-11-19 15:20 UTC, merged