6965 complete a leapp module
sleuthkit/autopsy pull request #6478
Opened 2020-11-20 14:56 UTC by markmckinnon

2020-11-23 19:04 UTC, kellykelly3 commented
@markmckinnon when you get a moment could you please fix the merge conflicts?  Thanks!

2020-11-23 19:38 UTC, kellykelly3 commented
@markmckinnon Please make sure the methods all have there appropriate headers and that  the files are formatted.

2020-12-01 21:59 UTC, kellykelly3 commented
@markmckinnon Format ALeappAnalyzerIngestModule.  There is some weird spacing.  And fix merge conflicts.

2020-12-01 22:00 UTC, kellykelly3 requested changes

2020-12-03 19:08 UTC, markmckinnon commented on Core/src/org/sleuthkit/autopsy/modules/leappanalyzers/ALeappAnalyzerIngestModule.java
> +    private void processALeappFs(Content dataSource, Case currentCase, DataSourceIngestModuleProgress statusHelper, String directoryToProcess) {
Added comments.

2020-12-03 19:09 UTC, markmckinnon commented on Core/src/org/sleuthkit/autopsy/modules/leappanalyzers/ALeappAnalyzerIngestModule.java
> +    private ProcessBuilder buildaLeappCommand(Path moduleOutputPath, String sourceFilePath, String aLeappFileSystemType) {
Added comments

2020-12-07 16:06 UTC, kellykelly3 approved these changes

2020-12-07 16:36 UTC, merged