7918 oo viewer cr only
sleuthkit/autopsy pull request #7260
Opened 2021-09-13 19:31 UTC by wschaeferB

2021-09-14 20:39 UTC, wschaeferB commented
Should be reviewed after https://github.com/sleuthkit/autopsy/pull/7258

2021-09-22 16:10 UTC, rcordovano requested changes

2021-09-22 16:10 UTC, rcordovano commented on Core/src/org/sleuthkit/autopsy/centralrepository/contentviewer/DataContentViewerOtherCases.java
> +        //The result of this is that the Other Occurrences viewer could be enabled but without a correltion attributes in some situations.
Misspelling, grammar:  "without a correltion attributes"

2021-09-22 16:13 UTC, rcordovano approved these changes

2021-09-22 16:13 UTC, merged